name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'API Environment to fetch posts from'
        required: false
        default: 'prod'
        type: choice
        options:
        - prod
        - dev
      theme:
        description: 'Site theme'
        required: false
        default: 'dark'
        type: choice
        options:
        - dark
        - light
      skip_posts_fetch:
        description: 'Skip fetching posts from API (use existing data)'
        required: false
        default: false
        type: boolean

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NEXT_PUBLIC_BASE_PATH: /nuraweb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        env:
          NEXT_PUBLIC_BASE_PATH: /nuraweb
          NEXT_PUBLIC_DEFAULT_THEME: ${{ github.event.inputs.theme || 'dark' }}
          NEXT_PUBLIC_API_BASE_URL: https://lynzm5kprh.execute-api.ap-south-1.amazonaws.com/${{ github.event.inputs.environment || 'prod' }}
          NEXT_PUBLIC_SITE_URL: https://arunrajan6600.github.io/nuraweb
          # Environment variables for the prebuild posts fetch (only if not skipping)
          API_BASE_URL: ${{ github.event.inputs.skip_posts_fetch == 'true' && '' || format('https://lynzm5kprh.execute-api.ap-south-1.amazonaws.com/{0}', github.event.inputs.environment || 'prod') }}
          API_STAGE: ${{ github.event.inputs.environment || 'prod' }}
          ADMIN_USERNAME: ${{ github.event.inputs.skip_posts_fetch == 'true' && '' || secrets.ADMIN_USERNAME }}
          ADMIN_PASSWORD: ${{ github.event.inputs.skip_posts_fetch == 'true' && '' || secrets.ADMIN_PASSWORD }}
        run: npm run build

      - name: Deployment Summary
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "## Manual Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "- **API Environment**: ${{ github.event.inputs.environment || 'prod' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Theme**: ${{ github.event.inputs.theme || 'dark' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Skip Posts Fetch**: ${{ github.event.inputs.skip_posts_fetch || 'false' }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Triggered by**: @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
